version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - /mnt/C/Users/ALS/Documents/GitHub/Adv-ML-First-Module/adv_ml_first_module/data:/adv-ml-first-module/data